const express=require('express');
const bodyParser=require('body-parser');
const mongoMovie=require('./mongoose');
const app=express();
app.use(bodyParser.json());
app.post('/movie/add', mongoMovie.addMovie);
app.post('/schedule/add', mongoMovie.addSchedule);
app.post('/user/add', mongoMovie.addUser);
app.post('/ticket/add', mongoMovie.addTicket);
app.listen(5000);